SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B USING (BOOK_ID)
JOIN AUTHOR A USING (AUTHOR_ID)
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 01
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY 1, 3 DESC