SELECT A.USER_ID, A.NICKNAME, 
    CONCAT(A.CITY, " ", A.STREET_ADDRESS1, " ", A.STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTRING(A.TLNO, 1, 3), "-", SUBSTRING(A.TLNO, 4, 4), "-", SUBSTRING(A.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER A
JOIN USED_GOODS_BOARD B ON B.WRITER_ID = A.USER_ID
GROUP BY B.WRITER_ID 
HAVING COUNT(B.BOARD_ID) >= 3
ORDER BY 1 DESC