WITH FILTERED_APPOINTMENT AS (
    SELECT A.APNT_NO, A.PT_NO, A.MCDP_CD, A.APNT_YMD, A.MDDR_ID
    FROM APPOINTMENT A
    WHERE A.APNT_YMD LIKE '2022-04-13%'
    AND A.APNT_CNCL_YN = 'N'
    AND A.MCDP_CD = 'CS'
)

SELECT FA.APNT_NO, P.PT_NAME, FA.PT_NO, FA.MCDP_CD, D.DR_NAME, FA.APNT_YMD
FROM FILTERED_APPOINTMENT FA
JOIN DOCTOR D ON FA.MDDR_ID = D.DR_ID
JOIN PATIENT P USING (PT_NO)
ORDER BY FA.APNT_YMD;