SELECT A.ID, B.FISH_NAME, A.LENGTH AS LENGTH
FROM FISH_INFO A 
JOIN FISH_NAME_INFO B USING (FISH_TYPE)
WHERE (A.FISH_TYPE, A.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                            FROM FISH_INFO
                            GROUP BY FISH_TYPE)
ORDER BY 1