SELECT CONCAT("/home/grep/src/", A.BOARD_ID, "/", A.FILE_ID, A.FILE_NAME, A.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE A
JOIN USED_GOODS_BOARD B USING (BOARD_ID)
WHERE VIEWS IN (SELECT MAX(VIEWS)
               FROM USED_GOODS_BOARD)
ORDER BY A.FILE_ID DESC